package ge.btu.flowershop.ui.auth

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException

/**
 * "Continue with Google" button. Reads the OAuth web client id generated by the
 * google-services plugin at runtime (so the app still compiles before Firebase is set up).
 */
@Composable
fun GoogleSignInButton(
    onIdToken: (String) -> Unit,
    onError: (String) -> Unit,
    enabled: Boolean = true,
    modifier: Modifier = Modifier,
) {
    val context = LocalContext.current
    val webClientId = remember {
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        if (resId != 0) context.getString(resId) else ""
    }

    val launcher = rememberLauncherForActivityResult(
        ActivityResultContracts.StartActivityForResult(),
    ) { result ->
        runCatching {
            GoogleSignIn.getSignedInAccountFromIntent(result.data)
                .getResult(ApiException::class.java)
                .idToken
        }.onSuccess { token ->
            if (token != null) onIdToken(token) else onError("No Google ID token returned")
        }.onFailure { onError("Google sign-in cancelled") }
    }

    OutlinedButton(
        onClick = {
            if (webClientId.isEmpty()) {
                onError("Google sign-in needs Firebase to be configured first")
                return@OutlinedButton
            }
            val options = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(webClientId)
                .requestEmail()
                .build()
            val client = GoogleSignIn.getClient(context, options)
            client.signOut() // force the account chooser each time
            launcher.launch(client.signInIntent)
        },
        enabled = enabled,
        modifier = modifier.fillMaxWidth(),
    ) {
        Text("Continue with Google")
    }
}
